import type { Metadata } from "next";
import { Science_Gothic } from "next/font/google";
import "./globals.css";
import { TanstackProvider } from "./components/provider/tanstack-provider";
import { Providers } from "./providers";

const scienceGothic = Science_Gothic({
  variable: "--font-science-gothic",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${scienceGothic.variable}  antialiased`}>
        <Providers>
          <TanstackProvider>{children}</TanstackProvider>
        </Providers>
      </body>
    </html>
  );
}
